# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Quality

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  detekt:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Cache Gradle Folders
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches/
          ~/.gradle/wrapper/
        key: cache-gradle-${{ hashFiles('gradle/libs.versions.toml') }}
        restore-keys: |
          cache-gradle-
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run analysis
      run: ./gradlew detektAll
